name: Setup Bun
description: Setup bun environment with cache and install dependencies
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - run: bun install --frozen-lockfile
      shell: bash
