name: cd
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  common-ci:
    uses: ./.github/workflows/common-jobs.yml
    secrets: inherit

  supabase-deploy:
    needs: common-ci
    if: needs.common-ci.outputs.supabase-ci-result == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: supabase-deploy
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref ${{ env.SUPABASE_PROJECT_ID }}
      - run: supabase db push
