name: cd
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml

  supabase-deploy:
    needs: ci
    if: needs.ci.outputs.supabase-changed == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: supabase-deploy
    defaults:
      run:
        working-directory: apps/syllabus-api
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref ${{ env.SUPABASE_PROJECT_ID }}
      - run: supabase db push
